openapi: 3.0.0
info:
  title: Simple API [MVC Pattern]
  version: 1.0.0
  
paths:
# Register a new user ....🚀
  /api/users/register:
    post:
      tags:
        - User
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 
          
# Login an user ....💥
  /api/users/login:
    post:
      tags:
        - User
      summary: Login an user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: 

# Find many user ....🚀
  /api/users/findManyUser:
    get:
      tags:
        - User
      summary: Find many user account.
      responses:
        '200':
          description: 

          
                
