openapi: 3.0.0
info:
  title: Simple API [MVC Pattern]
  version: 1.0.0
  
paths:
# Register a new user ....🚀
  /api/users/register:
    post:
      tags:
        - Authentication
      summary: Register a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: 
          
# Login an user ....💥
  /api/users/login:
    post:
      tags:
        - Authentication
      summary: Login an user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: 

# Find many user ....🚀
  /api/users/findManyUser:
    get:
      tags:
        - Find User
      summary: Find many user account
      responses:
        '200':
          description: 

# Find one user by ID ....🔥
  /api/users/findOne/{userId}:
    get:
      tags:
        - Find User
      summary: Find one user by Id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type : string
      responses: 
        '200':
          description: 

# Ban User by Id 
  /api/users/ban/{userId}:
    delete:
      tags:
        - Ban User
      summary: Ban User by Id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type : string
      responses: 
        '200':
          description: 

# Find many ban user
  /api/users/ban/findMany:
    get:
      tags:
        - Ban User
      summary: Find many ban user account
      responses:
        '200':
          description: 

# UnBan User by Id 
  /api/users/unBan/{userId}:
    patch:
      tags:
        - Ban User
      summary: UnBan User by Id
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type : string
      responses: 
        '200':
          description: 

          
                
